import { NextResponse } from "next/server";
import bcrypt from "bcryptjs";
import { z } from "zod";
import { supabase } from "@/lib/db";
import { logger } from "@/lib/logger";

export const runtime = "nodejs";

const schema = z.object({
  email: z.string().email(),
  password: z.string().min(6),
  name: z.string().optional(),
  role: z.enum(["student", "teacher"]).default("student"),
});

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { email, password, name, role } = schema.parse(body);

    // Check if user already exists
    const { data: existingUser, error: checkError } = await supabase
      .from('users')
      .select('id')
      .eq('email', email)
      .single();

    if (checkError && checkError.code !== 'PGRST116') {
      logger.error({ error: checkError }, "Error checking existing user");
      return NextResponse.json({ error: "Database error" }, { status: 500 });
    }

    if (existingUser) {
      return NextResponse.json(
        { error: "User already exists" },
        { status: 400 }
      );
    }

    // Hash password
    const hashedPassword = await bcrypt.hash(password, 10);

    // Insert user using Supabase client (id is auto-generated by database)
    const { data: newUser, error: insertError } = await supabase
      .from('users')
      .insert({
        email,
        password_hash: hashedPassword,
        name: name || email.split('@')[0],
        role,
      } as any)
      .select('id')
      .single();

    if (insertError) {
      logger.error({ error: insertError }, "Error inserting user");
      return NextResponse.json({ error: "Failed to create user" }, { status: 500 });
    }

    const userId = (newUser as any)?.id;
    logger.info({ userId, email, role }, "User registered successfully");

    return NextResponse.json(
      { message: "User registered successfully", userId },
      { status: 201 }
    );
  } catch (err: any) {
    logger.error({ 
      error: err.message, 
      stack: err.stack
    }, "Registration error");
    return NextResponse.json({ error: err.message || "Internal error" }, { status: 500 });
  }
}
